version: "3"
services:
   elastic:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
     container_name: elastic
     ports:
       - "9200:9200"
     restart: always
     privileged: true
     environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
     volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./plugins:/usr/share/elasticsearch/plugins