version: "3"
services:

   wordpress-mysql:
     image: mysql:latest
     container_name: wordpress-mysql
     ports:
       - "3306:3306"
     command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci     
     restart: always
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_ROOT_PASSWORD: docker233
     privileged: true
  
       
   wordpress:
     depends_on:
       - wordpress-mysql
     image: wordpress:latest
     container_name: wordpress
     ports:
       - "2021:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wordpress-mysql:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: docker233
     privileged: true
     volumes:
      - ~/testing-env/wordpress/wordpress:/var/www/html:rw