version: "3"
services:

   mynginx:
     image: nginx:latest
     container_name: mynginx
     restart: always
     privileged: true
     stdin_open: true
     tty: true
     ports:
      - "8090:80"
     volumes:
      - ~/testing-env/webdev/nginx/log:/var/log/nginx:rw
      - ~/testing-env/webdev/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ~/testing-env/webdev/nginx/conf/conf.d:/etc/nginx/conf.d:rw
      - ~/testing-env/webdev/frontend:/usr/share/nginx:rw
  
   watchtower:
     image: containrrr/watchtower:latest
     container_name: watchtower
     restart: always
     privileged: true
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock