version: "3"
services:

   mynginx:
     image: nginx:latest
     container_name: mynginx
     restart: always
     privileged: true
     stdin_open: true
     tty: true
     ports:
      - "8090:80"
     volumes:
      - ./nginx/log:/var/log/nginx:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:rw
      - ./frontend:/usr/share/nginx:rw
      